# Generated by Django 4.2.8 on 2025-11-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('database', 'Database')], max_length=20)),
                ('data', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('line', 'Çizgi Grafik'), ('bar', 'Çubuk Grafik'), ('pie', 'Pasta Grafik'), ('scatter', 'Scatter'), ('heatmap', 'Heatmap')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('x_axis', models.CharField(blank=True, max_length=255, null=True)),
                ('y_axis', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregation', models.CharField(blank=True, choices=[('sum', 'Toplam'), ('average', 'Ortalama'), ('count', 'Sayı'), ('min', 'Minimum'), ('max', 'Maksimum')], max_length=20, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='api.dashboard')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datasource')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
