# Generated by Django 6.0.1 on 2026-01-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
