# Generated by ChatGPT on 2026-01-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datasource_column_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='connection_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
