# Generated by Django 6.0.1 on 2026-02-12 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datasource_connection_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='type',
            field=models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('database', 'Database')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('line', 'Çizgi Grafik'), ('bar', 'Çubuk Grafik'), ('pie', 'Pasta Grafik'), ('scatter', 'Scatter'), ('heatmap', 'Heatmap')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['user', 'updated_at'], name='dashboard_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['user', 'uploaded_at'], name='datasrc_user_upload_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['user', 'type'], name='datasrc_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['dashboard', 'created_at'], name='widget_dash_created_idx'),
        ),
    ]
