# Generated by Django 6.0.1 on 2026-05-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisession',
            name='model_name',
            field=models.CharField(default='gemini-2.0-flash', max_length=100),
        ),
    ]
